services:
  tool-calls-agent:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true          # Enable TTY
    stdin_open: true   # Keep stdin open
    environment:
      - TERM=xterm-256color
    models:
      qwen2_5:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: MODEL_RUNNER_CHAT_MODEL
      
models:
  qwen2_5:
    model: ai/qwen2.5:latest
